In [50]:
import pandas as pd

# Load the crime data into a DataFrame
crime_data = pd.read_csv("Crime_Data_20240210.csv")

crime_data.head()

C:\Users\Tejas\AppData\Local\Temp\ipykernel_14588\1291657911.py:4: DtypeWarning: Columns (1,10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  crime_data = pd.read_csv("Crime_Data_20240210.csv")


Case and Offense Case Number Reported Date       Nature Of Call  \
0    180094593-35A   180094593    10/22/2018  NARCOTIC VIOLATIONS   
1    200085517-90Z   200085517    11/03/2020               HARASS   
2    210012743-240   210012743    02/20/2021           AUTO THEFT   
3    190047946-35A   190047946    06/04/2019  NARCOTIC VIOLATIONS   
4    190031427-90D   190031427    04/13/2019                  DWI   

                From Date Offense  \
0  10/22/2018 06:15:00 PM     35A   
1  08/12/2020 05:18:00 AM     90Z   
2  02/20/2021 08:27:59 PM     240   
3  06/04/2019 01:33:49 AM     35A   
4  04/13/2019 02:44:37 AM     90D   

                                         Description  \
0  HSC 481.115(B) Poss CS PG 1 <1G 35A DRUG/NARCOTIC   
1                             PC 42.07(C) Harassment   
2  PC 31.03(E)(4)(A)AUTO Theft>$1500<$20K (Auto t...   
3  HSC 481.117(B) Poss CS PG 3 <28G 35A DRUG/NARC...   
4  PC 49.04 Driving While Intoxicated 90D DRIVING...   

                    Block Address        City State Beat Division  \
0        700 CALIFORNIA PKWY N WB  FORT WORTH    TX  J13      NaN   
1             1300 MARLBOROUGH DR  FORT WORTH    TX  I16    South   
2         SANDY LN & EDERVILLE RD  FORT WORTH    TX  H15     East   
3   OAK GROVE RD / E IH 20 FWY EB         NaN    TX  I17      NaN   
4  WEST FWY SR WB / GREEN OAKS RD         NaN    TX  L11      NaN   

   Council District Attempt Complete  Location Type   Location Description  \
0               NaN                C           13.0  13 HIGHWAY/ROAD/ALLEY   
1               8.0                C           20.0      20 RESIDENCE/HOME   
2               5.0                C           18.0  18 PARKING LOT/GARAGE   
3               NaN                C           13.0  13 HIGHWAY/ROAD/ALLEY   
4               NaN                C           13.0  13 HIGHWAY/ROAD/ALLEY   

                                   Location  
0                                       NaN  
1  (32.640426597727426, -97.33851074771222)  
2                                       NaN  
3                                       NaN  
4                                       NaN

In [51]:
# Selecting subset of columns
subset = crime_data[["Case Number", "From Date", "Nature Of Call", "Location"]]

subset.head()

Case Number               From Date       Nature Of Call  \
0   180094593  10/22/2018 06:15:00 PM  NARCOTIC VIOLATIONS   
1   200085517  08/12/2020 05:18:00 AM               HARASS   
2   210012743  02/20/2021 08:27:59 PM           AUTO THEFT   
3   190047946  06/04/2019 01:33:49 AM  NARCOTIC VIOLATIONS   
4   190031427  04/13/2019 02:44:37 AM                  DWI   

                                   Location  
0                                       NaN  
1  (32.640426597727426, -97.33851074771222)  
2                                       NaN  
3                                       NaN  
4                                       NaN

In [68]:
# Number of rows before cleaning
rows_before_cleaning = subset.shape[0]
print("Number of rows before cleaning:", rows_before_cleaning)

# Remove rows with missing location values
cleaned_data = subset.dropna(subset=['Location'])

# Number of rows after cleaning
rows_after_cleaning = cleaned_data.shape[0]
print("Number of rows after cleaning:", rows_after_cleaning)


cleaned_data.head()


Number of rows before cleaning: 1305931
Number of rows after cleaning: 1281064


Case Number               From Date     Nature Of Call  \
1    200085517  08/12/2020 05:18:00 AM             HARASS   
5    210038831  05/22/2021 01:21:23 AM            ASSAULT   
8    210028773  04/18/2021 11:04:00 PM         AG ASSAULT   
9    190055743  06/28/2019 07:50:02 PM              ARSON   
11   210081343  10/09/2021 04:14:53 PM  ASSAULT BY THREAT   

                                    Location  
1   (32.640426597727426, -97.33851074771222)  
5     (32.7645696823948, -97.22700512799878)  
8    (32.68435373680007, -97.26198404688067)  
9   (32.748462645443354, -97.31747166100152)  
11  (32.692104326130725, -97.25332588069044)

In [71]:
# Convert 'From Date' column to datetime format
cleaned_data['From Date'] = pd.to_datetime(cleaned_data['From Date'], errors='coerce')

# Filter the cleaned_data DataFrame to keep only rows with 'From Date' in the last 5 years
filtered_data = cleaned_data[cleaned_data['From Date'].dt.year > 2018]

# Print the number of rows before and after filtering
print("Number of rows before filtering:", len(cleaned_data))
print("Number of rows after filtering:", len(filtered_data))

filtered_data.head()

Number of rows before filtering: 1281064
Number of rows after filtering: 287695


C:\Users\Tejas\AppData\Local\Temp\ipykernel_14588\738301821.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data['From Date'] = pd.to_datetime(cleaned_data['From Date'], errors='coerce')


Case Number           From Date     Nature Of Call  \
1    200085517 2020-08-12 05:18:00             HARASS   
5    210038831 2021-05-22 01:21:23            ASSAULT   
8    210028773 2021-04-18 23:04:00         AG ASSAULT   
9    190055743 2019-06-28 19:50:02              ARSON   
11   210081343 2021-10-09 16:14:53  ASSAULT BY THREAT   

                                    Location  
1   (32.640426597727426, -97.33851074771222)  
5     (32.7645696823948, -97.22700512799878)  
8    (32.68435373680007, -97.26198404688067)  
9   (32.748462645443354, -97.31747166100152)  
11  (32.692104326130725, -97.25332588069044)

In [77]:
# Split the 'Location' column into latitude and longitude components
cleaned_data[['Latitude', 'Longitude']] = cleaned_data['Location'].str.strip('()').str.split(', ', expand=True)

# Convert latitude and longitude to numeric
cleaned_data['Latitude'] = pd.to_numeric(cleaned_data['Latitude'])
cleaned_data['Longitude'] = pd.to_numeric(cleaned_data['Longitude'])

# Find the northeasternmost, northwesternmost, southeasternmost, and southwesternmost location values
northeast = (cleaned_data['Latitude'].max(), cleaned_data['Longitude'].max())
northwest = (cleaned_data['Latitude'].max(), cleaned_data['Longitude'].min())
southeast = (cleaned_data['Latitude'].min(), cleaned_data['Longitude'].max())
southwest = (cleaned_data['Latitude'].min(), cleaned_data['Longitude'].min())

# Print the results
print("Northeasternmost location:", northeast)
print("Northwesternmost location:", northwest)
print("Southeasternmost location:", southeast)
print("Southwesternmost location:", southwest)

C:\Users\Tejas\AppData\Local\Temp\ipykernel_14588\3541204365.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data[['Latitude', 'Longitude']] = cleaned_data['Location'].str.strip('()').str.split(', ', expand=True)
C:\Users\Tejas\AppData\Local\Temp\ipykernel_14588\3541204365.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data['Latitude'] = pd.to_numeric(cleaned_data['Latitude'])


Northeasternmost location: (33.04838570688878, -97.03398575738294)
Northwesternmost location: (33.04838570688878, -97.59986520191327)
Southeasternmost location: (32.55303567867901, -97.03398575738294)
Southwesternmost location: (32.55303567867901, -97.59986520191327)


C:\Users\Tejas\AppData\Local\Temp\ipykernel_14588\3541204365.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data['Longitude'] = pd.to_numeric(cleaned_data['Longitude'])


In [81]:
import numpy as np

# Define the boundaries of the grid based on the four corners found previously
lat_min, lat_max = southwest[0], northeast[0]
lon_min, lon_max = southwest[1], northeast[1]

# Calculate the latitude and longitude intervals for the grid
lat_interval = (lat_max - lat_min) / 10
lon_interval = (lon_max - lon_min) / 10

# Create a 10x10 grid with integer values
grid = np.zeros((10, 10), dtype=int)

# Iterate over the data and increment the corresponding grid value for each crime
for index, row in cleaned_data.iterrows():
    lat_index = int((row['Latitude'] - lat_min) // lat_interval)
    lon_index = int((row['Longitude'] - lon_min) // lon_interval)
    
    # Ensure that the index falls within the grid
    lat_index = min(max(lat_index, 0), 9)
    lon_index = min(max(lon_index, 0), 9)
    
    grid[lat_index, lon_index] += 1

# Print the grid
print("Grid with crime counts:")
print(grid)


Grid with crime counts:
[[     0      0     17    879   7734   3092      5      0      0      0]
 [     0      3    202  30829  62870   8315    179      0      0      0]
 [     0    262   2731  67496  82186  37802  15146      0      0      0]
 [   228   6546  79232  54971 117957 127847  82662   6008      0      0]
 [     0   5947   7641  25954 106941  49810  49346  36533     42      0]
 [     0    389   2297  24878  29162  17101     17   1879   3105  15348]
 [     0     97   2419   9877  10704  37798     62      0      0      0]
 [     0      0    122   1724   8413  18842    771      0      0      0]
 [     0      0      0   3674    542   8109   1433      0      0      0]
 [     0      0      0      7   1359   3434     88      0      0      0]]
